using System;
using System.Collections.Generic;

namespace Incontrl.Sdk.Models
{
    /// <summary>
    /// Configuration settings for myData.
    /// </summary>
    public class AadeMyDataSettings
    {
        /// <summary>
        /// The base URL according to the environment used.
        /// </summary>
        public string BaseUrl { get; set; }
        /// <summary>
        /// The selected user ID.
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// The subscription key generated by AADE.
        /// </summary>
        public string SubscriptionKey { get; set; }
        /// <summary>
        /// List of options based on document type.
        /// </summary>
        public IEnumerable<TransmissionOption> TransmissionOptions { get; set; }
    }

    /// <summary>
    /// Specifies the way used to publish invoices to AADE.
    /// </summary>
    public class TransmissionOption
    {
        /// <summary>
        /// The document type ID.
        /// </summary>
        public Guid DocumentTypeId { get; set; }
        /// <summary>
        /// The transmission type.
        /// </summary>
        public TransmissionType Type { get; set; }
    }

    /// <summary>
    /// The transmission type.
    /// </summary>
    public enum TransmissionType
    {
        /// <summary>
        /// Manuaal send.
        /// </summary>
        Manual = 0,
        /// <summary>
        /// Send automatically.
        /// </summary>
        Auto = 1,
        /// <summary>
        /// Send at the end of the day.
        /// </summary>
        EndOfDay = 2
    }
}
