using System;

namespace Incontrl.Sdk.Models
{
    public class Transaction
    {
        public Guid Id { get; set; }

        /// <summary>
        /// Usually this is the transaction UID.
        /// if not available it stores an hash generated by the transaction properties so that it is considered unique.
        /// </summary>
        public string UniqueId { get; set; }

        public TransactionType Type { get; set; }
        public DateTime Completed { get; set; }
        public string MerchantReference { get; set; }
        public string Description { get; set; }
        public Money Value { get; set; } = new Money();
        public Money Balance { get; set; } = new Money();
        public Guid? BatchId { get; set; }
        public Guid SubscriptionId { get; set; }
    }
}
